/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#00458e",
        "surface-container": "#edeeef",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-container": "#af4900",
        "background": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "on-surface-variant": "#414753",
        "outline-variant": "#c1c6d5",
        "surface-dim": "#d9dadb",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "tertiary-fixed-dim": "#ffb692",
        "on-secondary-fixed": "#131d23",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed": "#341100",
        "tertiary": "#883700",
        "on-secondary-fixed-variant": "#3e484f",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d9e4ec",
        "inverse-primary": "#aac7ff",
        "on-primary": "#ffffff",
        "primary": "#004e9f",
        "on-primary-fixed": "#001b3e",
        "on-secondary-container": "#5b666d",
        "secondary-container": "#d9e4ec",
        "on-background": "#191c1d",
        "primary-container": "#0066cc",
        "primary-fixed-dim": "#aac7ff",
        "tertiary-fixed": "#ffdbcb",
        "outline": "#727784",
        "on-tertiary-fixed-variant": "#793000",
        "surface": "#f8f9fa",
        "secondary": "#556067",
        "on-primary-container": "#dfe8ff",
        "surface-tint": "#005cba",
        "on-tertiary-container": "#ffe3d6",
        "secondary-fixed-dim": "#bdc8d0",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3132",
        "error": "#ba1a1a",
        "primary-fixed": "#d7e3ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "1rem",
        "stack-sm": "0.5rem",
        "stack-lg": "1.5rem",
        "stack-md": "1rem",
        "stack-xs": "0.25rem",
        "margin-mobile": "1rem",
        "container-max": "1264px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-mono": ["Geist"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "code-block": ["Geist"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "1.0", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "code-block": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}